### PR TITLE
Adds support for using multiple "tsconfig.json" files.

### PR DESCRIPTION
**Pull request by capricorn86**
Thank you for a great extension!

I am working on a project that requires me to work with multiple tsconfig.json files, therefore I have made some improvements to your extension by adding support for this. Hopefully, this is something that you also can benefit from.

**Added features:**
- Support for using multiple "tsconfig.json" files.
- Some improvements to performance by killing compilations of same file and use of cache for "tsc" path.

### CODE REVIEW

**Comment by morissonmaciel** [comment]
Hello @capricorn86,
Thanks for the interest in improving the extension. 
Definitely, multiple tsconfig files were indeed in the roadmap and I'm glad someone has made it simple through a clean implementation. 👍

I was just reviewing your code when realized that I maybe need a good scenario for reviewing and debugging tests.

**Can you share the basic structure used to do your tests?**

I was wondering something like:
* One workspace
* Two Typescript enabled modules
* Each module with a simple `tsconfig.json` file
* Each `tsconfig.json` file with a simple output `out` folder

And maybe for a extended test:
* One workspace
* Two Typescript enabled modules
* One module with a simple `tsconfig.json` file
* This `tsconfig.json` file with a simple output `out` folder
* Other module only with pure `.ts` files 

Waiting for your answer.
Thanks in advance

**Review by morissonmaciel — CHANGES_REQUESTED** [review]
@capricorn86,
Unfortunately, some tests failed for the first scenario (one workspace with two root _modules_ folders) where was expected success in these steps:

1. ⛔Adding a blank `tsconfig.json` file in one `root-folder` result in the following error

anotacao 2018-12-04 132826
>Note: error was fixed in my additional pull request commit 

2. ⛔Saving an empty `tsconfig.json` file, result in the following error:

anotacao 2018-12-04 133826
>Note: the error was fixed in my additional pull request commit 

3. ⛔After fixing above issues, the extension couldn't find a proper `tsc` compiler to use with one of the `root-folder`

anotacao 2018-12-04 140823
>Note: a workaround (half-way for complete fixing) was made in pull request commit - this deserves a discussion due to incomplete implementation of `vscode` API for managing and dealing with correct workspace folder info by child file path.

4. ⛔Using file uri `path` property result in error on Windows environment:

anotacao 2018-12-04 145658
>Note: error was fixed, using `fsPath` property, compliance to the current OS, and with a hack in `tsc` command splitting and joining paths using `Path.sep` (path separator for current OS). Need testes IN MAC / UNIX environment.

5. ⚠The following code is producing too much extension reloads (create/dispose of)

anotacao 2018-12-04 174029
>Observations: Destroying the extension to reconstruct is spamming too much `tsconfig.json` found message and other notifications related to extension creation lifecycle.

### 👎🏼Secondary feature was not attended (broken)⛔
Unfortunately, using `muti-root workspace` isn't considering a folder without a `tsconfig.json` file. This was the first feature implemented by extension.

The problem maybe resides in the following code. Only `tsconfig.json` based configuration is considered in implementation.

I couldn't fix without altering entire logic. Maybe you want to consider review this method and/or discuss!?

```javascript
    public watch() {
        if (!this.isWatching) {
            this.isWatching = true;
            this.output = window.createOutputChannel("TypeScript Auto Compiler");
            this.statusChannel = new TypeScriptCompilerStatusChannel();

            this.output.appendLine('Looking for "tsconfig.json" files..');
            this.output.appendLine('');

            this.watchTsConfigFiles();
            this.watchProjects().then(() => {
                this.statusChannel.updateStatus('$(eye) TS [ON]',
                    'TypeScript Auto Compiler is ON - Watching file changes.', 'white');
                this.output.appendLine('');
                this.output.appendLine('Watching for file changes..');
            });
        }
    }
```
### 👍All other features are working well (including the fixes related above)

anotacao 2018-12-04 134312

anotacao 2018-12-04 134919

anotacao 2018-12-04 135005

**Comment by capricorn86** [comment]
Hello @morissonmaciel,

I have added a fix for the issue where all watchers are reloaded when a tsconfig.json file is changed, removed or added. Can you please review it?

Best regards,
David

**Review by morissonmaciel — APPROVED** [review]

**Comment by morissonmaciel** [comment]
@capricorn86 everything went fine.
Pull request now merged. Preparing the extension package.
You were mentioned in the implementation credits

Thanks one again. 👏🏽

**Comment by morissonmaciel** [comment]
Proper working - case 1
captura de tela 2018-12-06 as 16 51 52

Proper working - `tscconfig.json` change and no `tsc` installation
captura de tela 2018-12-06 as 16 57 54

**Comment by capricorn86** [comment]
@morissonmaciel nice to hear that everything is working as expected and that it is merged 😀 Thank you!

**Pull request merged**
